# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a84f62e85580e981d1ed996913c9495927dccc8f4e4e35604c95bb0ea38a5c5603634b82edbb6d020fabf6a636dd3819c0c181c913e43f03695a5eab09356c0

test:
  secret_key_base: 1cebb0a1e199899d33f63ce27c0cf194b056a1cf41df0939f472032557068914909bbba75ac493af854a8f17b45491a9dfccba64a325c1d44c4fb8a93fd13441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
